### PR TITLE
10280 support CJK overwrite

### PR DESCRIPTION
**Pull request by xlazom00**

### CODE REVIEW

**Comment by vladimir-kraus** [comment]
The overwriting does not work in the following cases:
1) when user uses cursor up/down keys to navigate through the IME list and then confirms with enter
2) when use clicks on an item in the IME list with a mouse

In these cases the following character/characters is/are not overwritten.

**Comment by xlazom00** [comment]
@vladimir-kraus should be ok now

**Comment by vladimir-kraus** [comment]
Unfortunately it does not work well. When I enter a Japanese character (e.g. the one which I get by pressing letter 'a') with overwrite mode and then confirm with Enter, the whole rest of the text (to the right of the entered character) is overwritten, instead of just one character.

**Comment by xlazom00** [comment]
@vladimir-kraus what about now ?

**Comment by vladimir-kraus** [comment]
It seems to work well now.

**Comment by vladimir-kraus** [comment]
Everything OK now.

**Pull request merged**
